import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/header";
import TabContentWithTabBar from "@/widgets/TabContentWithTabBar";
import Sidebar from "@/widgets/sidebar";
import Footer from "@/widgets/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
      >
        <Header />
        <div className="flex flex-1 overflow-hidden">
          {/* 사이드바 */}
          <Sidebar />

          {/* 메인 콘텐츠 영역과 푸터를 포함하는 컨테이너 */}
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* 메인 콘텐츠 영역 - 푸터 공간을 제외한 영역 */}
            <div className="flex-1 overflow-hidden bg-gray-50">
              <TabContentWithTabBar />
            </div>

            {/* 푸터 영역 - 메인 콘텐츠 아래에 배치 */}
            <Footer />
          </div>
        </div>

        {/* children은 숨김 처리 또는 제거 가능 */}
        <div className="hidden">{children}</div>
      </body>
    </html>
  );
}