import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/widgets/header";
import TabContentWithTabBar from "@/widgets/TabContentWithTabBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex flex-col`}
      >
        <Header />
        {/*
          main을 w-full h-full, overflow-auto로 설정
          => 전체 화면 폭을 차지하고, 내용이 넘치면 스크롤
        */}
        <main className="flex-1 w-full h-full overflow-auto bg-gray-50">
          <TabContentWithTabBar />
        </main>

        {/* children은 숨김 처리 또는 제거 가능 */}
        <div className="hidden">{children}</div>
      </body>
    </html>
  );
}
